version: '3.9'

name: employee-management

volumes:
  employee_postgres_data:
    driver: local

services:
  db:
    container_name: postgres_employee
    image: postgres:13.3
    volumes:
      - employee_postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: employee_db
      POSTGRES_USER: employee
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"

  backend:
    container_name: employee-management-service
    image: berndheidemann/employee-management-service:1.1.1
    #    image: berndheidemann/employee-management-service_without_keycloak:1.1
    environment:
      spring.datasource.url: jdbc:postgresql://db:5432/employee_db
      spring.datasource.username: employee
      spring.datasource.password: secret
    ports:
      - "8089:8089"
    depends_on:
      - db

  frontend:
    container_name: employee-management-frontend
    build: ..
    ports:
      - "4200:80"
